ProjectASP.NET/Controllers/GameController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using ProjectASP.NET.Filter;
using ProjectASP.NET.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectASP.NET.Controllers
{
    [DisableBasic]
    public class GameController : Controller
    {
        private ICRUDGameRepository repository;

        public GameController(ICRUDGameRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult AddGame()
        {
            ViewData["Username"] = HttpContext.Session.GetString("Username");
            return View();            
        }

        [HttpPost]
        public IActionResult Add(GameModel game)
        {
            if (ModelState.IsValid)
            {
                ViewData["Username"] = HttpContext.Session.GetString("Username");
                return View("ConfirmGame", repository.AddGame(game));
            }
            else
            {
                ViewData["Username"] = HttpContext.Session.GetString("Username");
                return View("AddGame");
            }

        }

        public IActionResult Index()
        {
            ViewData["Username"] = HttpContext.Session.GetString("Username");
            return View(repository.FindAllGames());
        }

        public IActionResult EditGame(int id)
        {
            ViewData["Username"] = HttpContext.Session.GetString("Username");
            return View(repository.FindGameById(id));
        }

        public IActionResult Edit(GameModel game, UserModel user)
        {
            ViewData["Username"] = HttpContext.Session.GetString("Username");
            repository.UpdateGame(game, user);
            return View("Index", repository.FindAllGames());
        }

        public IActionResult DeleteGame(int id)
        {
            ViewData["Username"] = HttpContext.Session.GetString("Username");
            repository.DeleteGame(id);
            return View("Index", repository.FindAllGames());
        }
    }
}

ProjectASP.NET/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using ProjectASP.NET.Filter;
using ProjectASP.NET.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ProjectASP.NET.Controllers
{
    [DisableBasic]
    public class UserController : Controller
    {
        private readonly ICRUDUserRepository repository;

        public UserController(ICRUDUserRepository repository)
        {
            this.repository = repository;
        }

        public IActionResult Index()
        {
            ViewData["Username"] = HttpContext.Session.GetString("Username");
            return View("Index",repository.FindAllUsers());
        }

        public IActionResult EditUserPage(string id)
        {
            ViewData["Username"] = HttpContext.Session.GetString("Username");
            return View(repository.FindUserById(id));
        }
    }
}

ProjectASP.NET/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity;
@inject SignInManager<IdentityUser> signInMagager;

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjectASP.NET</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 ml-5 mr-5">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjectASP.NET</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (signInMagager.IsSignedIn(User))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">User List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Game" asp-action="Index">Game List</a>
                        </li>
                    }
                </ul>
                <div>
                    @if (signInMagager.IsSignedIn(User))
                    {
                        <a class="nav-link text-primary" asp-controller="Account" asp-action="Logout">Logout @User.Identity.Name</a>
                    }
                    else
                    {
                        <a class="btn btn-sm btn-outline-dark mr-2" asp-controller="Account" asp-action="Register">Register</a>
                        <a class="btn btn-sm btn-primary active" asp-controller="Account" asp-action="Login">Login</a>
                    }

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ProjectASP.NET - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>